version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack5
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
